Trigger: Test AWS deploy pipeline - Updated Docker Images

diff --git a/.github/workflows/deploy-infra.yaml b/.github/workflows/deploy-infra.yaml
--- a/.github/workflows/deploy-infra.yaml
+++ b/.github/workflows/deploy-infra.yaml
@@ -80,7 +80,10 @@ jobs:
         run: |
           REQUIRED=( TF_PROJECT_NAME TF_ENVIRONMENT TF_EKS_CLUSTER_NAME TF_EKS_CLUSTER_VERSION TF_GITOPS_REPO_URL TF_TARGET_REVISION TF_ARGOCD_APP_MANIFEST_PATH TF_AVAILABILITY_ZONE_1 TF_AVAILABILITY_ZONE_2 TF_STATE_BUCKET TF_LOCK_TABLE )
           for key in "${REQUIRED[@]}"; do
-            [ -z "${!key}" ] && echo "Missing secret $key" && exit 1
+            if [ -z "${!key}" ]; then
+              echo "Missing secret $key"
+              exit 1
+            fi
           done
 
       - name: Generate secrets.auto.tfvars.json
